### ISSUE TITLE
What is a devDependency?

### ISSUE THREAD

**Issue by Daemach** [elpete/whoops#7]
I really like the template.  But could sure use some code that I can copy/paste into relevant files...  I did install using --saveDev maybe that's it?  What does that do?

Most of your users (well me, anyway) may not be as experienced and well-read as you.  This is your chance to show off your knowledge and gain wider adoption due to "it-just-works"-ness :)

**Comment by elpete** [comment]
A `devDependency` is not installed when you `box install —production`. `devDependencies` should not be installed in your production environment. Since whoops exposes a lot of information not suitable for production, it should be installed as a `devDependency`. A different error template should be used in production.
